version: '3'

services:  

  db:
    image: mongo
    container_name: todo-mongo-db
    ports:
      - 27017:27017

  dev:
    image: node:11
    container_name: todo-web-app
    volumes:
      - .:/usr/src/service ## for development, when our files change, the files in the container also need to change.
    working_dir: /usr/src/service ## We will mount our current directory . to /usr/src/service in the container. We will also need to tell docker where our “working directory” is. Meaning — what directory did we put the code in
    command: npm run server-create-task-test #server #initialize
    ports: 
      - 3000:3000
      - 1235:1235
      - 7777:7777